module.exports = [
    {
        src:[
            './build/js/plugin/**',
            './build/js/common/**',
            './build/validate/validate.js',
            './build/validate/sub/login.js',

        ],
        concatName:'main.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/swiper.min.js',
            './build/js/page/index.js',
        ],
        concatName:'index.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/file.js',
            './build/validate/sub/memorial.js',
            './build/js/page/memorial/add.js',
        ],
        concatName:'memorial-add.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/photo.js',
            './build/js/ui/photo-handler.js',
            './build/js/ui/sacrifice-offset.js',
            './build/js/ui/sacrifice-move.js',
            './build/js/ui/sacrifice-more.js',
            './build/js/ui/sacrifice.js',
            './build/js/ui/fire-work.js',
            './build/js/ui/note-show.js',
            './build/js/ui/smoke.js',
            './build/js/page/memorial/venue.js',
            './build/js/page/memorial/venue-product.js',
        ],
        concatName:'memorial-venue.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/memorial/index.js',
        ],
        concatName:'memorial-index.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/swiper.min.js',
            './build/js/ui/page.js',
            './build/js/ui/file.js',
            './build/js/ui/move.js',
            './build/js/ui/cut.js',
            './build/js/ui/album.js',
            './build/js/ui/progress.js',
            './build/js/data/city.data.js',
            './build/js/ui/city-select.js',
            './build/js/ui/birthday.js',
            './build/js/page/user/index.js',
            './build/js/page/user/extend/**',
            './build/validate/sub/user/**',
        ],
        concatName:'user-index.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/page.js',
            './build/js/page/news/index.js',
            './build/js/page/news/detail.js',
        ],
        concatName:'news-index.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/page.js',
            './build/js/page/search/index.js',
        ],
        concatName:'search-index.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/opinion/index.js',
        ],
        concatName:'opinion-index.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/validate/sub/genealogy.js',
            './build/js/ui/move.js',
            './build/js/ui/genealogy.js',
            './build/js/page/genealogy/input.js',
        ],
        concatName:'genealogy-input.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/genealogy/index.js',
        ],
        concatName:'genealogy-index.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/move.js',
            './build/js/ui/genealogy.js',
            './build/js/page/genealogy/detail.js',
        ],
        concatName:'genealogy-detail.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/swiper.min.js',
            './build/js/page/user/detail.js',
        ],
        concatName:'user-detail.js',
        destPath:'./build/js/build/'
    },
];